export type ContentTypes =
    | "application/json"
    | "application/xml"
    | "application/x-www-form-urlencoded"
    | "multipart/form-data"
    | "application/octet-stream"
    | "text/plain"
    | "text/html"
    | "text/css"
    | "text/javascript"
    | "application/javascript"
    | "application/pdf"
    | "application/rtf"
    | "text/csv"
    | "application/ld+json"
    | "image/png"
    | "image/jpeg"
    | "image/gif"
    | "image/webp"
    | "image/svg+xml"
    | "image/avif"
    | "audio/mpeg"
    | "audio/ogg"
    | "audio/wav"
    | "audio/webm"
    | "video/mp4"
    | "video/ogg"
    | "video/webm"
    | "application/vnd.api+json"
    | "application/openapi+json"
    | "application/openapi+yaml"
    | (string & {})

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS' | 'HEAD' | 'TRACE'
