name: Publish Template Package to npm
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        working-directory: ./template
        run: npm install
      
      - name: Build package
        working-directory: ./template
        run: npm run build
      
      - name: Publish to npm
        working-directory: ./template
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}